name: Deploy to Pages with Secret
on: push
jobs: 
  env:
    MEANING_OF_LIFE: ${{secrets.MEANING_OF_LIFE}}, 
    BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}, 
    WHATEVER_YOU_WANT: ${{secrets.WHATEVER_YOU_WANT}}
  run: echo `Virker dette: ${MEANING_OF_LIFE}, ${MEANING_OF_LIFE}, ${WHATEVER_YOU_WANT}`;

    