name: Deploy to Pages with Secret
on: push
env: 
  MEANING_OF_LIFE: ${{secrets.MEANING_OF_LIFE}}, 
  BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}, 
  WHATEVER_YOU_WANT: ${{secrets.WHATEVER_YOU_WANT}}
jobs: 
  steps:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Virker dette?"
